export const productCategories = [
  "Android Smart TV Box/Air Mouse",
  "Attendance Machines",
  "Barcode Scanners, Printer & POS Devices",
  "Bluetooth Hands free",
  "Bluetooth Headphone",
  "Bluetooth Music Receiver",
  "Bluetooth+Usb Speakers",
  "Cash Drawer & Counting Machines",
  "Cameras/Security Gadgets",
  "Connectors",
  "Converters",
  "Gaming Accessories",
  "HDD Case",
  "HDMI Cables",
  "HDMI Wifi Dongle",
  "Keyboard/Mouse/Pad",
  "Laptop Charger",
  "Mobile accessories",
  "Microphones",
  "Miscellaneous",
  "Networking",
  "Networking Cables",
  "Safe Lockers",
  "Power Bank",
  "Presenter",
  "Printer Cables",
  "Projector Ceilng Mount",
  "Projector/Projector Screens",
  "Smart Watch",
  "Splitters and Switches",
  "Wired Hands Free",
  "Tripod, Mobile & Laptop Stands",
  "USB Cables",
  "USB Hub and Power Socket",
  "VGA Cables",
  "LED TVs & Television Accessories",
] as const;

export function categorySlug(category: string) {
  return category.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}
